spring.application.name=library-demo

#debug=true





####

# In-Memory JDBC Connection Settings (MySQL Compatibility Mode)
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;VARIABLE_BINARY=TRUE;NON_KEYWORDS=KEY,VALUE,TYPE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
###


spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=file:/home/surreal/Applications/Java/Luminar/projects/library-demo/library-demo/data.sql
#JPA
#spring.jpa.show-sql=true

#Thymleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#HTTPS SUPPORT
#443
server.port=8443
insecure_redirection.http.port=8080
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-alias=tomcatSSL
server.ssl.key-store-password=LtUsJe6BSB2XUwRi
server.ssl.key-store-type=PKCS12

app.security.enforce-https=false

#REMEBER ME
remember_me.key=9Dizr1Sd8V8UpDXk
remember_me.valididty=3600

#DUES
app.dues.borrow-duration=1
app.dues.fine-per-day=4


#INITIAL USERNAME, PASSWORD
#spring.security.user.name=admin
#spring.security.user.password=pass

#DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

#
setup.initial.fill-roles-table=false

pdf-creation-url=http://localhost:8600/api/pdf/create


eureka.client.serviceUrl.defaultZone=http://localhost:8800/eureka/