spring.application.name=library-demo
server.port=8100
#debug=true
server.ssl.enabled=false
insecure_redirection.http.port=0

#DATABASE CONNECTION#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=Ash
spring.datasource.password=Ash

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Thymleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#HTTPS SUPPORT
#443



#REMEBER ME
remember_me.key=9Dizr1Sd8V8UpDXk
remember_me.valididty=3600

#DUES
app.dues.borrow-duration=1
app.dues.fine-per-day=4


#INITIAL USERNAME, PASSWORD
#spring.security.user.name=admin
#spring.security.user.password=pass

#DEBUG
#logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

#
setup.initial.fill-roles-table=false

pdf-creation-url=http://localhost:8600/api/pdf/create


eureka.client.serviceUrl.defaultZone=http://localhost:8800/eureka/